---
- name: ensure systemd service
  include_role:
    name: "damex.systemd_service"
  vars:
    systemd_service_name: "{{ systemd_timesyncd_service_name }}"
    systemd_service_restart_on: "{{ systemd_timesyncd_conf.changed }}"
