---
- name: ensure timesyncd.conf
  template:
    src: "timesyncd.conf.j2"
    dest: "{{ systemd_timesyncd_conf_file }}"
    group: "root"
    owner: "root"
    mode: 0644
  register: systemd_timesyncd_conf
  become: true
